== Create Greeting Service

Create a simple Quarkus project as a starting point - the _Greeting Service_.
A default REST endpoint is generated.
While this tutorial utilizes the mvn command line tooling,
projects can also be generated at http://code.quarkus.io[code.quarkus.io] using a Web UI.

. Go to the project's base directory and create project using maven
+
--
.Terminal 1
[source,bash]
----
cd firststeps/working

mvn io.quarkus:quarkus-maven-plugin:1.9.0.Final:create \
    -DprojectGroupId=org.acme \
    -DprojectArtifactId=greeting \
    -DclassName="org.acme.GreetingResource" \
    -Dpath="/greeting" \
    -Dextensions=resteasy-jsonb
----
--
+
// *********************************************
'''

. Optional: To see a list of available extensions, type:

+
--

.Terminal 1
[source,bash]
----
mvn quarkus:list-extensions
----
--
+
// *********************************************
'''

. Open project in your favorite IDE.
Open GreetingResource.java and peruse the JAX-RS source code

+
--
.GreetingResource.java
[source,java]
----
package org.acme;

import javax.ws.rs.GET;
import javax.ws.rs.Path;
import javax.ws.rs.Produces;
import javax.ws.rs.core.MediaType;

@Path("/greeting")
public class GreetingResource {

    @GET
    @Produces(MediaType.TEXT_PLAIN)
    public String hello() {
        return "hello";
    }
}
----

NOTE: Quarkus does not require a JAX-RS Application class, but will use it
if provided.
In addition, Quarkus RESTful resources are singletons
(`@javax.inject.Singleton`).
These are developer convenience features.
These points are covered in the
https://quarkus.io/guides/getting-started#the-jax-rs-resources[Quarkus Getting Started Guide].
--

+
// *********************************************
'''

. Start Quarkus in developer mode

+
--
.Terminal 1
[source,bash]
----
$ mvn compile quarkus:dev
----
--
+
// *********************************************
'''

. Check that the endpoint returns _hello_

+
--
.Terminal 2
[source,bash]
----
curl -i localhost:8080/greeting
----
.Terminal 2 Output
....
HTTP/1.1 200 OK
Content-Length: 5
Content-Type: text/plain;charset=UTF-8

hello
....
--
+
// *********************************************
'''

. Try out live reload.
In the hello() method, replace _hello_ with _Howdy_
and save the file
+
.GreetingResource.java
[source,java]
----
public class GreetingResource {

    @GET
    @Produces(MediaType.TEXT_PLAIN)
    public String hello() {
        return "Howdy"; // <1>
    }
}
----
<1> Replace _Hello_ with _howdy_

+

.Terminal 2
[source,bash]
----
curl -i localhost:8080/greeting
----
+
.Terminal 2 Output
----
HTTP/1.1 200 OK
Content-Length: 5
Content-Type: text/plain;charset=UTF-8

Howdy
----

+
// *********************************************
'''

. Change _Howdy_  back to _hello_
+
// *********************************************
'''

. In GreetingResource.java, create a list of Strings:
+
--
.GreetingResource.java
[source,java]
----
@Path("/greeting")
public class GreetingResource {
    List<String> greetings = new ArrayList<>(); // <1>
----
<1> Add this line
--
+
// *********************************************
'''

. Add a method called `listGreetings()` at the "/list" path that returns the greetings as a JSON array
+
--
.GreetingResource.java
[source,java]
----
@GET
@Path("/list")
@Produces(MediaType.APPLICATION_JSON)
public List<String> listGreetings() {
    return greetings;
}
----
--
+
// *********************************************
'''

. Check the output
+
.Terminal 2
--
[source,bash]
----
curl -i localhost:8080/greeting/list
----
--

+
--

.Terminal 2 Output
....
HTTP/1.1 200 OK
Content-Length: 2
Content-Type: application/json

[]
....
--
