== Quarkus Debugging and Command Mode

This section covers Quarkus debugging and command mode.
Debugging is straightforward but there are some useful things to know.
Command mode allows Quarkus to run command line applications.

. Disable debugging
+
--
.Terminal 1
[source,shell script]
----
mvn quarkus:dev -Ddebug=false       # <1>
----
<1> -Ddebug=false disables debugging.
-Ddebug=true enables debuggingon port 5005 (default)
--
+
// *********************************************
'''

. Customize debugging port
+
--
.Terminal 1
[source, shell script]
----
mvn quarkus:dev -Ddebug=5006       # <1>
----
<1> Debug on port 5006
--
+
// *********************************************
'''
. Suspend JVM until debugger attached
+
--
.Terminal 1
[source,properties]
----
mvn quarkus:dev -Dsuspend=y
----
--
+
// *********************************************
'''

. Create firststeps application
+
--
.Terminal 2
[source,shell script]
----
cd working                                                 # <1>
mvn io.quarkus:quarkus-maven-plugin:1.9.0.Final:create \   # <2>
    -DprojectGroupId=org.acme \
    -DprojectArtifactId=firststeps \
    -DclassName="org.acme.FirstStepsResource" \
    -Dpath="/firststeps"
----
<1> Go to the top-level project then working subdirectory
<2> Create the first-steps application
--
+
// *********************************************
'''

. Add class FirstStepsMain
+
--
.FirstStepsMain.java
[source,java]
----
@QuarkusMain                                                     // <1>
public class FirstStepsMain implements QuarkusApplication {      // <2>
    @Override
    public int run(String... args) throws Exception {            // <3>
        System.out.println("******* " + args[0]                  // <4>
                           + " " + args[1]
                           + " ********");
        return 0;                                                // <5>
    }
}
----
<1> Application entry point
<2> QuarkusApplication interface requires a run() method
<3> Run method that passes in command line arguments
<4> Print out command line arguments
<5> Return value back to shell (or whatever invoked application)
--
+
// *********************************************
'''

. Test the main method
+
--
.Terminal 2
[source,shell script]
----
mvn quarkus:dev \
    -Dquarkus.http.port=8088 \         # <1>
    -Ddebug=5088 \                     # <2>
    -Dquarkus.args="Hello1 Hello2"     # <3>
----
<1> Set a different port to avoid conflict with _Greeting Service_
<2> Set a different debug port to avoid conflict with _Greeting Service_
<3> Define command line arguments to _FirstSteps Service_.

.Terminal 2 output
[source,text]
----
...

******* Hello1 Hello2 ********               <1>

...

Quarkus application exited with code 0       <2>
Press Enter to restart or Ctrl + C to quit   <3>
----
<1> Application output
<2> The application exited with a return value of 0
<3> Quarkus dev mode works with command line applications.
Make a change and press <Entr>.
--
+
// *********************************************
'''

. Run as a jar file
+
--
.Terminal 2
[source,shell script]
----
mvn clean package
java -jar \
    -Dquarkus.http.port=8088                        # <1>
    -Ddebug=5088 \
    target/firststeps-1.0-SNAPSHOT-runner.jar  \
    Hello1 Hello2                                   # <2>

----
<1> System properties defined *before* jar file defined.
With developer mode, they are defined after the maven goal
<2> Command line args specified at end of command line

.Terminal 2 output
[source,text]
----
...

2020-10-18 13:37:29,552 INFO  [io.quarkus] (main) Installed features: [cdi, resteasy]
******* Hello1 Hello2 ********
2020-10-18 13:37:29,610 INFO  [io.quarkus] (main) firststeps stopped in 0.045s

...
----
--
+
// *********************************************
'''

. Add main method so application can be run from IDE
+
--
.FirstStepsMain.java
[source,java]
----
public static void main(String... args ) {
    Quarkus.run(FirstStepsMain.class, args);  // <1>
}
----
<1> Call Quarkus.run on a QuarkusApplication implementation class
--
+
// *********************************************
'''

. Add microprofile-rest-client and resteasy-jsonb extensions
+
--
.Terminal 2
[source,shell script]
----
mvn quarkus:add-extension \
    -Dextensions=rest-client,resteasy-jsonb
----

.Terminal 2 output
[source,text]
----
...

✅ Extension io.quarkus:quarkus-rest-client has been installed
✅ Extension io.quarkus:quarkus-resteasy-jsonb has been installed
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------

...
----
--
+
// *********************************************
'''

. Create GreetingsRestClient to invoke GreetingService REST endpoints.
The MicroProfile Rest Client API is beyond the scope of this tutorial.

+
--
.GreetingsRestClient.java
[source,java]
----
@Path("/greeting")
@RegisterRestClient(baseUri = "http://localhost:8080")
public interface GreetingsRestClient {

    @GET
    @Produces(MediaType.TEXT_PLAIN)
    public String hello();

    @GET
    @Path("/list")
    @Produces(MediaType.APPLICATION_JSON)
    public List<String> listGreetings();

    @GET
    @Path("/list/random")
    @Produces(MediaType.TEXT_PLAIN)
    public String randomGreeting();
}
----
--
+
// *********************************************
'''

. Update FirstStepsMain to invoke _Greeting Service_.
A `QuarkusMain` is an `ApplicationScoped` bean so it can inject
and invoke other CDI beans.
+
--
.FirstStepsMain.java
[source,java]
----
@Inject
@RestClient                                             // <1>
GreetingsRestClient client;

@Override
public int run(String... args) throws Exception {
    System.out.println("******* " + args[0]
                       + " " + args[1]
                       + " ********");
    System.out.println(client.listGreetings());         // <2>
    return 0;
}
----
<1> Inject the `GreetingsRestClient`
<2> Print the greetings list
--
+
// *********************************************
'''

. Run the application from the IDE
+
--
.IDE output
[source,text]
----
...

******* Hello1 Hello2 ********
[Howdy from app.prop, Hola from app.prop, Hello from app.prop]

...
----
--
+
// *********************************************
'''

. Wait for application to exit.
+
--
.FirstStepsMain.java
[source,java]
----
    @Override
    public int run(String... args) throws Exception {
        System.out.println("******* " + args[0]
                           + " " + args[1]
                           + " ********");
        System.out.println(client.listGreetings());
        Quarkus.waitForExit();                          // <1>
        return 0;
    }
----
<1> Wait for the application to exit

NOTE: To exit an application using `Quarkus.waitForExit()`, call
`Quarkus.asyncExit()`.
--
+
// *********************************************
'''

. Stop application started from IDE
+
--
--
+
// *********************************************
'''

. Run the application from the IDE
+
--
.Terminal 2
[source,shell script]
----
mvn quarkus:dev \
    -Dquarkus.http.port=8088 \
    -Ddebug=5088 \
    -Dquarkus.args="Hello1 Hello2"
----

.Terminal 2 output
[source,text]
----
...

******* Hello1 Hello2 ********
[Howdy from app.prop, Hola from app.prop, Hello from app.prop]

... <1>
----
<1> The application is still running
--
