== Quarkus Packaging

This section covers how to package and run applications.

// *********************************************
'''

. Create a thinjar
+
--
.Terminal 2 (firststeps application)
[source,shell script]
----
mvn clean package
----

.Terminal 2
[source,shell script]
----
java \
    -Dquarkus.http.port=8088 \                            # <1>
    -Ddebug=5088 \
    -jar target/firststeps-1.0-SNAPSHOT-runner.jar \      # <2>
    Hello1 Hello2                                         # <3>
----
<1> When executing a runnable jar file, the system properties
belong before the jar file name
<2> Two jar files are generated.
`firststeps-1.0-SNAPSHOT.jar` is generated by the maven compiler plugin.
The Quarkus plugin generates the `firststeps-1.0-SNAPSHOT-runner.jar`.
The runnable Quarkus application is the latter.
<3> Command line arguments belong after the jar file.

Feel free to check various endpoints to validate they still work.
--
+
// *********************************************
'''

. Create an uber-jar
+
--
.Terminal 2
[source,shell script]
----
mvn clean package -Dquarkus.package.type=uber-jar
----

.Terminal 2
[source,shell script]
----
java \
    -Dquarkus.http.port=8088 \
    -Ddebug=5088 \
    -jar target/firststeps-1.0-SNAPSHOT-runner.jar \
    Hello1 Hello2
----

Feel free to check various endpoints to validate they still work.
--
+
// *********************************************
'''

. Quarkus cannot run H2 in-memory database in native mode, even thought it will
successfully compile to native.
For this reason, the production binary will use a PostgreSQL database.
So, let's install the PostgreSQL JDBC extension (driver).
+
--
.Terminal 2
[source,shell script]
----
mvn quarkus:add-extension -Dextensions=jdbc-postgres
----
--
+
// *********************************************
'''

. Start PostgreSQL
+
--
.Terminal 3
[source,shell script]
----
docker run \
    -d \
    --ulimit memlock=-1:-1 \
    -it \
    --rm=true \
    --memory-swappiness=0 \
    --name postgres \
    -e POSTGRES_USER=quarkus \
    -e POSTGRES_PASSWORD=quarkus \
    -e POSTGRES_DB=quarkus \
    -p 5432:5432 \
    postgres:11.2
----
--
+
// *********************************************
'''

. Configure PostgreSQL.
This will still drop-and-create and import data for a "production"
configuration, but hey, it's only a tutorial.
+
--
.application.properties
[source,properties]
----
# PostgreSQL "Production" database configuration

%prod.quarkus.datasource.db-kind=postgresql
%prod.quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/quarkus
%prod.quarkus.datasource.username=quarkus
%prod.quarkus.datasource.password=quarkus
%prod.quarkus.hibernate-orm.sql-load-script=import.sql
----
--
+
// *********************************************
'''

. Compile to a native binary
+
--
.Terminal 3
[source,shell script]
----
mvn clean verify -Pnative
----
--
+
// *********************************************
'''

. Run the native binary
+
--
.Terminal 2
[source,shell script]
----
target/firststeps-1.0-SNAPSHOT-runner \
  -Dquarkus.http.port=8088 \
  -Ddebug=5088 \
  Hello1 Hello2
----

.Terminal 2 output
----
...

[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.acme.SecurityTest
2020-10-20 20:52:50,710 INFO  [io.qua.ely.sec.pro.dep.ElytronPropertiesProcessor] (build-11) Configuring from MPRealmConfig
2020-10-20 20:52:52,087 INFO  [org.ecl.jet.uti.log] (main) Logging initialized @2988ms to org.eclipse.jetty.util.log.Slf4jLog
2020-10-20 20:52:52,196 INFO  [org.ecl.jet.ser.Server] (main) jetty-9.4.18.v20190429; built: 2019-04-29T20:42:08.989Z; git: e1bc35120a6617ee3df052294e433f3a25ce7097; jvm 11.0.8+10-jvmci-20.2-b03
...

[INFO] Tests run: 6, Failures: 0, Errors: 0, Skipped: 0                         <1>

...

[firststeps-1.0-SNAPSHOT-runner:99017]    classlist:  10,020.47 ms,  1.07 GB
[firststeps-1.0-SNAPSHOT-runner:99017]        (cap):   3,440.47 ms,  1.07 GB
[firststeps-1.0-SNAPSHOT-runner:99017]        setup:   5,313.04 ms,  1.07 GB
20:53:16,064 INFO  [org.hib.Version] HHH000412: Hibernate ORM core version 5.4.22.Final
20:53:16,070 INFO  [org.hib.ann.com.Version] HCANN000001: Hibernate Commons Annotations {5.1.0.Final}
20:53:16,105 INFO  [org.hib.dia.Dialect] HHH000400: Using dialect: io.quarkus.hibernate.orm.runtime.dialect.QuarkusPostgreSQL10Dialect
20:53:31,923 INFO  [org.jbo.threads] JBoss Threads version 3.1.1.Final
[firststeps-1.0-SNAPSHOT-runner:99017]     (clinit):     816.13 ms,  4.21 GB
[firststeps-1.0-SNAPSHOT-runner:99017]   (typeflow):  22,936.15 ms,  4.21 GB
[firststeps-1.0-SNAPSHOT-runner:99017]    (objects):  30,186.20 ms,  4.21 GB
[firststeps-1.0-SNAPSHOT-runner:99017]   (features):   1,465.94 ms,  4.21 GB
[firststeps-1.0-SNAPSHOT-runner:99017]     analysis:  58,155.09 ms,  4.21 GB
[firststeps-1.0-SNAPSHOT-runner:99017]     universe:   2,623.30 ms,  4.20 GB
[firststeps-1.0-SNAPSHOT-runner:99017]      (parse):  10,878.09 ms,  5.69 GB
[firststeps-1.0-SNAPSHOT-runner:99017]     (inline):   9,625.10 ms,  7.36 GB
[firststeps-1.0-SNAPSHOT-runner:99017]    (compile):  43,520.46 ms,  7.59 GB
[firststeps-1.0-SNAPSHOT-runner:99017]      compile:  68,837.54 ms,  7.59 GB
[firststeps-1.0-SNAPSHOT-runner:99017]        image:   8,449.02 ms,  7.50 GB
[firststeps-1.0-SNAPSHOT-runner:99017]        write:   2,346.50 ms,  7.50 GB
[firststeps-1.0-SNAPSHOT-runner:99017]      [total]: 156,113.60 ms,  7.50 GB
[INFO] [io.quarkus.deployment.QuarkusAugmentor] Quarkus augmentation completed in 159737ms  <2>

...

[INFO] -------------------------------------------------------
[INFO]  T E S T S                                                                           <3>
[INFO] -------------------------------------------------------

...

2020-10-20 20:55:40,692 INFO  [io.quarkus] (main) firststeps 1.0-SNAPSHOT native (powered by Quarkus 1.9.0.Final) started in 0.114s. Listening on: http://0.0.0.0:8081

...

[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
----
<1> Tests are run in JVM mode as part of a Java build
<2> Compiled in 159 seconds
<3> Tests run against native binary
--
+
// *********************************************
'''

. Re-run tests on a native binary without having to re-compile the binary.
This is helpful since it takes 159s to re-compile a binary!
+
--
.Terminal 2
[source,shell script]
----
./mvnw test-compile failsafe:integration-test
----

.Terminal 2 output
[source,text]
----
...

[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
...

[INFO] Results:
[INFO]
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  8.153 s
[INFO] Finished at: 2020-10-20T21:09:40-07:00
[INFO] ------------------------------------------------------------------------
----
--
